manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: AYM1607
      url-base: https://github.com/AYM1607
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    # Driver du touchpad Azoteq IQS5xx (TPS43 / TPS65)
    - name: zmk-driver-azoteq-iqs5xx
      remote: AYM1607
      revision: 27321f0232b50f0af31eb27ff97d539933467ea4
  self:
    path: config
